# Numpy Arrays

In [2]:
# NumPy (Numerical Python) is a Python library used for:

    # Fast mathematical operations on large datasets
    # Arrays and matrices (instead of Python lists)
    # Linear algebra, statistics, Fourier transforms, random numbers, etc.
    # It is written in C internally → so it is much faster than native Python lists.

# Array Declarations

In [427]:
# Declaration of 1D, 2D, 3D, 4D and 5D Arrays

import numpy as np

# one dimensional array

ar0 = np.array(20)
print(type(ar0))
print("Dimension count : ",ar0.ndim)
print(ar0)
print()

arr0 = np.array((4,7,2,6,0,1,3,4,8))
print(type(arr0))
print("Dimension count : ",arr0.ndim)
print(arr0)
print()

arr1 = np.array([2,5,3,7,9,1,10])
print(type(arr1))
print("Dimension count : ",arr1.ndim)
print(arr1)
print()

#range array
arr6 = np.arange(1,10,2)
print("\nCreating 1D Array using arange function :\t",arr6)

# equally spaced 5 values between 0 and 1
arr7 = np.linspace(0,1,5)
print("Creating 1D Array using linspace function for equidistanced array element :\t",arr7)
print()

# creating an array of integer of 32bit
ar32 = np.array(np.arange(1,20,4), dtype = 'i4')
print(type(ar32))
print(ar32.dtype)
print(ar32)
print()

# creating array of string datatype
arr_str = np.array(["apple", "banana", "cherry"])
print(arr_str)
print(arr_str.dtype)
print()

sarr = np.array(["apple","mango","banana","grapes",'date','plum'], dtype= 'S')
print(type(sarr))
print(sarr.dtype)
print(sarr)
print()

arstr = np.array(['goa',123,"Mohan",45,True,None,45.23], dtype=str)
print(arstr)
print(arstr.dtype)
print()

# creating array of float datatype
arr_float = np.array([1.2, 3.5, 7.9, 10.0])
print(arr_float)
print(arr_float.dtype)
print()

arrf1 = np.array([-1.4, 2.4, -3.1], dtype=float)
print(arrf1)
print(arrf1.dtype)
print()

# creating array of complex datatype
arr_complex = np.array([1+2j, 3+4j, 5+6j])
print(arr_complex)
print(arr_complex.dtype)
print()

arcn = np.array([3-6j, 4, 5j], dtype=complex)
print(arcn)
print(arcn.dtype)
print()

# two dimensional array
arr2 = np.array([[2,5,3],[7,9,1]])
print(type(arr2))
print("Dimension count : ",arr2.ndim)
print(arr2)
print()

# array of zeros of 2 rows and 3 columns
arr3 = np.zeros((2,3))
print("Dimension count : ",arr3.ndim)
print(arr3)
print()

# array of ones having 3 rows and 2 columns
arr4 = np.ones((3,2))
print("Dimension count : ",arr4.ndim)
print(arr4)
print()

# 3D array 
# here one [row X col] makes 1 Layer and MORE THAN 1 LAYER makes it 3D
# here below in arr5, we have 2 layers so it is a 3D array

arr5 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [11,12,13],
        [14,15,16]
    ]
])
print(type(arr5))
print("Dimension count of arr5 is : ",arr5.ndim)
print(arr5)
print()

# 4D array 
# here one [row X col] makes 1 Layer and list of Layer makes it Block
# here below in arr6, we have 2 Blocks of 2 layers each, so this makes it a 4D array
arr6 = np.array([
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [3,2,1],
            [6,5,4]
        ]
    ],
    [
        [
            [5,6,7],
            [8,3,9]
        ],
        [
            [2,4,6],
            [1,3,5]
        ]
    ]
])
print(type(arr6))
print("Dimension count of arr6 is : ",arr6.ndim)
print(arr6)
print()

# making a 6D array

arr7 = np.array([1234], ndmin=6)
print(arr7)
print("Dimension of arr7 : ", arr7.ndim)
print()

# identity matrix
arr8 = np.eye(3)
print(arr8)
print()

# Random array of 2 column and 3 
arr9 = np.random.rand(2,3)
print(arr9)

<class 'numpy.ndarray'>
Dimension count :  0
20

<class 'numpy.ndarray'>
Dimension count :  1
[4 7 2 6 0 1 3 4 8]

<class 'numpy.ndarray'>
Dimension count :  1
[ 2  5  3  7  9  1 10]


Creating 1D Array using arange function :	 [1 3 5 7 9]
Creating 1D Array using linspace function for equidistanced array element :	 [0.   0.25 0.5  0.75 1.  ]

<class 'numpy.ndarray'>
int32
[ 1  5  9 13 17]

['apple' 'banana' 'cherry']
<U6

<class 'numpy.ndarray'>
|S6
[b'apple' b'mango' b'banana' b'grapes' b'date' b'plum']

['goa' '123' 'Mohan' '45' 'True' 'None' '45.23']
<U5

[ 1.2  3.5  7.9 10. ]
float64

[-1.4  2.4 -3.1]
float64

[1.+2.j 3.+4.j 5.+6.j]
complex128

[3.-6.j 4.+0.j 0.+5.j]
complex128

<class 'numpy.ndarray'>
Dimension count :  2
[[2 5 3]
 [7 9 1]]

Dimension count :  2
[[0. 0. 0.]
 [0. 0. 0.]]

Dimension count :  2
[[1. 1.]
 [1. 1.]
 [1. 1.]]

<class 'numpy.ndarray'>
Dimension count of arr5 is :  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]

<class 'numpy.ndarray'>
Dimension

# 1D Array Operations

In [412]:
# Element acesss by indexing and Slicing

ar1 = np.array([80,10,60,40,90,20])

# INDEXING
print("The first element of the array is  : ",ar1[0])
print("The last element of the array is : ",ar1[-1])
print("The 4th element of the array from begining is : ",ar1[3])
print("The 4th element of the array from last is : ",ar1[-4])
print()

# SLICING
print("The first 4 elements of the array from begining are  : ",ar1[0:4])
print("The reversed array is  : ",ar1[::-1])
print("The array with one element gap is \t",ar1[::2])


1D Array using arange function :	 [1 3 5 7 9]
1D Array using linspace function for equidistanced array element :	 [0.   0.25 0.5  0.75 1.  ]

The first element of the array is  :  80
The last element of the array is :  20
The 4th element of the array from begining is :  40
The 4th element of the array from last is :  60

The first 4 elements of the array from begining are  :  [80 10 60 40]
The reversed array is  :  [20 90 40 60 10 80]
The array with one element gap is 	 [80 60 90]


In [405]:
# Concatenating two 1D array

a1 = np.arange(1,20,3)
a2 = np.arange(2,20,4)
print("a1 is : ",a1)
print("a2 is : ",a2)
print("concatnation if a1 and a2 reults : ",np.concatenate((a1,a2)))
print()

# removing duplicacy from the 1D array
num = np.array([4,5,2,7,3,9,7,2,3,7,0,9,3,7,6,9,0])
print("current 1D array is : ",num)
uni = np.unique(num)
print("Unique number of the array are : ",uni)
print()

# getting the count of occurance of an element from the array
nm = np.array([4,5,2,7,3,1,4,2,3,6,2,3,4,6,4,2,1,2,4,4,5,4,3])
count_4 = np.sum(nm == 4)
place_4 = np.where(nm == 4)
print("we have total",count_4,"occurances of 4s in array at locations : ",place_4)
print()

# getting Unique elements of array, First indices of the unique elements and their total occurance in the array at once
nm_uni_index_count = np.unique( nm, return_index=True, return_counts=True)
print("Here we have Unique elements of array, First indices of the unique"
"elements and their total occurance in the array : \n",nm_uni_index_count)
print()

a1 is :  [ 1  4  7 10 13 16 19]
a2 is :  [ 2  6 10 14 18]
concatnation if a1 and a2 reults :  [ 1  4  7 10 13 16 19  2  6 10 14 18]

current 1D array is :  [4 5 2 7 3 9 7 2 3 7 0 9 3 7 6 9 0]
Unique number of the array are :  [0 2 3 4 5 6 7 9]

we have total 7 occurances of 4s in array at locations :  (array([ 0,  6, 12, 14, 18, 19, 21]),)

Here we have Unique elements of array, First indices of the uniqueelements and their total occurance in the array : 
 (array([1, 2, 3, 4, 5, 6, 7]), array([5, 2, 4, 0, 1, 9, 3]), array([2, 5, 4, 7, 2, 2, 1]))



In [404]:
# DELETETION OF THE ELEMENTS from the 1D array by index

print(nm)
nm = np.delete(nm,2)    # goto index 2 of the array nm and delete the index element
print(nm)

# deleting element from the 1D array by slicing indexwise
nm = np.delete(nm,np.s_[:10])    # start from index 0 go till index 9 , delete elements
# nm = np.delete(nm,np.s_[10:])    # start from index 10, go till last element, delete all
# nm = np.delete(nm,np.s_[3:13])    # start from index 3, go till 12 , delete all
# nm = np.delete(nm,np.s_[2:21:3])    # start from index 2, gotill index 20, delete element escaping 2 elemnts in between
print(nm)

[3 4 6 4 2 1 2 4 4 5 4 3]
[3 4 4 2 1 2 4 4 5 4 3]
[3]


In [418]:
# Ranging, Stacking, min, max, sum, standard deviation and variance function

ar3 = np.arange(2,15,3)
ar4 = np.arange(3,20,4)

print("1D array ar3 is : ",ar3)
print("1D array ar4 is : ",ar4)
print()

# verticle stacking of individual 1D array to make multi dimensional array
ar11 = np.vstack((ar3,ar4))
print("\nThe vertically stacked ar3 and ar4 results : \n\n",ar11)
print("\nThe dimension of vertically stacked array ar11 is : \t",np.ndim(ar11))


# horizontal stacking of individual 1D array to make one single 1D array
ar12 = np.hstack((ar3,ar4)) 
print("\nThe horizontally stacked ar3 and ar4 results : \n\n",ar12)
print("\nThe dimension of horizontally stacked array ar12 is : \t",np.ndim(ar12))

print("\nar3 ** 3 : ",ar3**3)
print("ar3 + ar4 : ",ar3 + ar4)
print("ar4 - ar3 : ",ar4 - ar3)
print("ar3 - ar4 : ",ar3 - ar4)
print("ar3 * ar4 : ",ar3 * ar4)
print("ar3 / ar4 : ",ar3 / ar4)
print("ar3 % ar4 : ",ar3 % ar4)
print()

print("The minimum value of ar3 and ar4 are ",ar3.min()," and ",ar4.min()," respectively")
print("The maximum value of ar3 and ar4 are ",ar3.max()," and ",ar4.max()," respectively")
print("The sum total of ar3 values and ar4 values are ",ar3.sum()," and ",ar4.sum()," respectively")
print("The mean value of ar3 and ar4 are ",ar3.mean()," and ",ar4.mean()," respectively")
print("The standard deviation value of ar3 and ar4 are ",ar3.std()," and ",ar4.std()," respectively")
print("The variance value of ar3 and ar4 are ",ar3.var()," and ",ar4.var()," respectively")

1D array ar3 is :  [ 2  5  8 11 14]
1D array ar4 is :  [ 3  7 11 15 19]


The vertically stacked ar3 and ar4 results : 

 [[ 2  5  8 11 14]
 [ 3  7 11 15 19]]

The dimension of vertically stacked array ar11 is : 	 2

The horizontally stacked ar3 and ar4 results : 

 [ 2  5  8 11 14  3  7 11 15 19]

The dimension of horizontally stacked array ar12 is : 	 1

ar3 ** 3 :  [   8  125  512 1331 2744]
ar3 + ar4 :  [ 5 12 19 26 33]
ar4 - ar3 :  [1 2 3 4 5]
ar3 - ar4 :  [-1 -2 -3 -4 -5]
ar3 * ar4 :  [  6  35  88 165 266]
ar3 / ar4 :  [0.66666667 0.71428571 0.72727273 0.73333333 0.73684211]
ar3 % ar4 :  [ 2  5  8 11 14]

The minimum value of ar3 and ar4 are  2  and  3  respectively
The maximum value of ar3 and ar4 are  14  and  19  respectively
The sum total of ar3 values and ar4 values are  40  and  55  respectively
The mean value of ar3 and ar4 are  8.0  and  11.0  respectively
The standard deviation value of ar3 and ar4 are  4.242640687119285  and  5.656854249492381  respectively
The variance

In [421]:
# Reshaping, Flattening, Splitting and Random functions

# Reshaping and flatening

ar4 = np.arange(1,13)
print(ar4)
print()

# reshaping the ar4 1d to 3X4 2D array
print(ar4.reshape(3,4))
print()

# reshaping the ar4 1d to 2X6 2D array
print(ar4.reshape(2,6))
print()

# reshaping the ar4 1D to 4X3 2D array
ar = ar4.reshape(4,3)
print(ar)
print()

# flatening the reshaping multi dimensional array into 1D array
farr = ar.flatten()
rvlar = ar.ravel()
print("flatten function result on ar : ",farr)
print()
print("ravel function result on ar : ",rvlar)
print()
# splitting the elements of array

# for equal splitting only
print(np.split(farr,4))
print()
# for equal and unequal splitting
print(np.array_split(farr,7))
print()

# random float number between 0 and 1
print(np.random.rand(5))

# random single digit between 1 and 50
print(np.random.randint(1,50))

# normal distribution
print(np.random.randn(4))
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

flatten function result on ar :  [ 1  2  3  4  5  6  7  8  9 10 11 12]

ravel function result on ar :  [ 1  2  3  4  5  6  7  8  9 10 11 12]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11]), array([12])]

[0.6111711  0.10294615 0.43053286 0.18268376 0.69383987]
7
[ 0.14968065 -0.43683222  0.05879978 -1.36000845]



# 2D Array Operations

In [420]:
# 2D array Element Acessing and inbuilt functions

ar2 = np.array([[2,5,3],[7,9,1]])
print(type(ar2))
print("\nThe 2D array is \n\n",ar2)
print()

# dimension of the array
print("This is a",ar2.ndim,"dimensional array.\n")

# total number of rows and columns of the array
print("\nThe number of rows and columns in the array is : ",ar2.shape)

# total element in the array
print("\nThe total number of elements in the array is : ",ar2.size)

# get the datatype of the array
print("The array contains ",ar2.dtype," type elements.\n")

print("The 3rd element 1st row is : ",ar2[0,2])
print("The 2nd element 2st row is : ",ar2[1,1])
print()

print("The 2nd column is : ", ar2[:,1])
print("The 1st row is : ", ar2[0,:])
print()

<class 'numpy.ndarray'>

The 2D array is 

 [[2 5 3]
 [7 9 1]]

This is a 2 dimensional array.


The number of rows and columns in the array is :  (2, 3)

The total number of elements in the array is :  6
The array contains  int64  type elements.

The 3rd element 1st row is :  3
The 2nd element 2st row is :  9

The 2nd column is :  [5 9]
The 1st row is :  [2 5 3]



In [386]:
# concatenating two 2D array

a2d1 = np.array([[1,2,3],[4,5,6]])
a2d2 = np.array([[10,20,30],[40,50,60]])
print("1st 2D array is :\n\n",a2d1)
print("\n2nd 2D array is :\n\n",a2d2)
print()

arrx = np.concatenate((a2d1,a2d2),axis = 1)
print("concatnation of a2d1 and a2d2 on axis 1 results : \n\n",arrx)
arry = np.concatenate((a2d1,a2d2),axis = 0)
print("\nconcatnation of a2d1 and a2d2 on axis 0 results : \n\n",arry)
print("\nDimension of new concatenated array : ",arry.ndim)
print()

1st 2D array is :

 [[1 2 3]
 [4 5 6]]

2nd 2D array is :

 [[10 20 30]
 [40 50 60]]

concatnation of a2d1 and a2d2 on axis 1 results : 

 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]

concatnation of a2d1 and a2d2 on axis 0 results : 

 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]

Dimension of new concatenated array :  2



In [381]:
# getting the count and place(indices) of any particular number in 2D array
arr2d = np.array([
    [1, 7, 2],
    [7, 3, 0],
    [4, 5, 7]
])
print("arr2d is : \n",arr2d)
print()

# Count how many 7s
count_7 = np.sum(arr2d == 7)
print("Number of 7s in 2D:", count_7)

# Indices of 7s
indices_7 = np.where(arr2d == 7)
result = list(map(lambda x: tuple(int(i) for i in x), zip(*indices_7)))
print("places of 7 in the array are \t",result)
print()

arr2d is : 
 [[1 7 2]
 [7 3 0]
 [4 5 7]]

Number of 7s in 2D: 3
places of 7 in the array are 	 [(0, 1), (1, 0), (2, 2)]



In [435]:
# DELETION of elements in 2D array [array_name, row/col number/s, axis = 0(row)/1(column)]

arr2d = np.arange(1, 13).reshape(3,4)
print("\nOriginal 2D array is :\n\n", arr2d)

# Delete the column 3 of the array
arr2dc3 = np.delete(arr2d, 3, axis = 1)
print("\nArray after deletion of the column 3 : \n\n",arr2dc3)

# Delete the row 1 of the array
arr2dr1 = np.delete(arr2d, 1 , axis = 0)
print("\nArray after deletion of the row 1 : \n\n",arr2dr1)

# Delete column indices 1:3 (i.e., cols 1 and 2)
arr2d_new = np.delete(arr2d, np.s_[1:3], axis= 1)
print("\nAfter deleting cols 1 to 2:\n\n", arr2d_new)

# Delete row indices 0:2 (i.e., rows 0 and 1)
arr2d_new2 = np.delete(arr2d, np.s_[0:2], axis= 0)
print("\nAfter deleting rows 0 to 1:\n\n", arr2d_new2)


Original 2D array is :

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array after deletion of the column 3 : 

 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

Array after deletion of the row 1 : 

 [[ 1  2  3  4]
 [ 9 10 11 12]]

After deleting cols 1 to 2:

 [[ 1  4]
 [ 5  8]
 [ 9 12]]

After deleting rows 0 to 1:

 [[ 9 10 11 12]]


In [422]:
# Linear Algebra functions

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# matrix multiplication
print(np.dot(A,B))
print()

# inverse of matrix
print(np.linalg.inv(A))
print()
print(np.linalg.inv(B))
print()

# determinant of matrix
print(np.linalg.det(A))
print()
print(np.linalg.det(B))
print()

# eigenvalue and eigenvector of matrix
print(np.linalg.eig(A))
print()
print(np.linalg.eig(B))
print()

[[19 22]
 [43 50]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[-4.   3. ]
 [ 3.5 -2.5]]

-2.0000000000000004

-2.000000000000005

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

EigResult(eigenvalues=array([-0.15206735, 13.15206735]), eigenvectors=array([[-0.75868086, -0.59276441],
       [ 0.65146248, -0.80537591]]))



# 3D Array Operations

In [401]:
# 3D array Element Acessing and inbuilt functions

print(type(arr5))
print(arr5)
print()

# dimension of the array
print("This is a",arr5.ndim,"dimensional array.")
print()

# total number of blocks, rows and columns of the array
print("The number of blocks, rows and columns in the array is : ",arr5.shape)

# total element in the array
print("The total number of elements in the array is : ",arr5.size)

# get the datatype of the array
print("The array contains ",arr5.dtype," type elements.")
print()

# INDEXING [layer,row,col]

print("The 3rd element 1st row of block 1 is : ",arr5[0,0,2])
print("The 2nd element 2st row of block 2 is : ",arr5[1,1,1])
print("The element on block 2 row 1 and col 3 is :",arr5[1,0,2])
print("The element on block 1 row 2 and col 1 is :",arr5[0,1,0])
# print()

#SLICING
print()
print("\nThe 2nd column of each block is : \n\n", arr5[:,:,1])
print("\nThe 2st row of each block is : \n\n", arr5[:,1,:])
print("\nThe 2nd column of 1st block is : \n\n", arr5[0,:,1])
print("\nThe 2st row of 2nd block is : \n\n", arr5[1,1,:])
print("\nThe all 2nd block is : \n\n", arr5[1,:,:])
print("\nThe first elemnt of each row of each block is : \n\n", arr5[:,:,0])
print("\nThe last elemnt of each row of each block is : \n\n", arr5[:,:,-1])
print("\nThe elemnets from block 1, row 1 and from col 1to col 2 : \n\n", arr5[0,0,0:2])
print("\nThe elemnets from block 2, col 1 to col 2 : \n\n", arr5[1,:,0:2])

<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]

This is a 3 dimensional array.

The number of blocks, rows and columns in the array is :  (2, 2, 3)
The total number of elements in the array is :  12
The array contains  int64  type elements.

The 3rd element 1st row of block 1 is :  3
The 2nd element 2st row of block 2 is :  15
The element on block 2 row 1 and col 3 is : 13
The element on block 1 row 2 and col 1 is : 4


The 2nd column of each block is : 

 [[ 2  5]
 [12 15]]

The 2st row of each block is : 

 [[ 4  5  6]
 [14 15 16]]

The 2nd column of 1st block is : 

 [2 5]

The 2st row of 2nd block is : 

 [14 15 16]

The all 2nd block is : 

 [[11 12 13]
 [14 15 16]]

The first elemnt of each row of each block is : 

 [[ 1  4]
 [11 14]]

The last elemnt of each row of each block is : 

 [[ 3  6]
 [13 16]]

The elemnets from block 1, row 1 and from col 1to col 2 : 

 [1 2]

The elemnets from block 2, col 1 to col 2 : 

 [[11 12]
 [14 15]]


In [397]:
# Getting the count and occurance indices of a particular element in 3D array

arr3d = np.array([
    [
        [7, 2, 7],
        [4, 7, 6]
    ],
    [
        [7, 8, 9],
        [6, 11, 7]
    ]
])
print("The 3D array is : \n\n",arr3d)

occr_7 = np.sum(arr3d == 7)
print("\nThere are ",occr_7," 7s present in the array.")

indices_7 = np.where(arr3d == 7)
print("\n7 is present in the array at : ",indices_7)
result = list(map(lambda x: tuple(int(i) for i in x), zip(*indices_7)))
print("\nPlaces of 7 in the array are :\n",result)

The 3D array is : 

 [[[ 7  2  7]
  [ 4  7  6]]

 [[ 7  8  9]
  [ 6 11  7]]]

There are  5  7s present in the array.

7 is present in the array at :  (array([0, 0, 0, 1, 1]), array([0, 0, 1, 0, 1]), array([0, 2, 1, 0, 2]))

Places of 7 in the array are :
 [(0, 0, 0), (0, 0, 2), (0, 1, 1), (1, 0, 0), (1, 1, 2)]


In [402]:
# DELETION of elements in 3D array

arr3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print("Original new 3D array :\n\n", arr3d)

# Delete block 1
arr3d_axis0 = np.delete(arr3d, 1, axis=0)
print("\nDelete block 1:\n\n", arr3d_axis0)
print()

# Delete block 0 and 1 using slicing
arr3d_axis02 = np.delete(arr3d, np.s_[0:2], axis=0)
print("\nArray after deletion of block 0 and 1:\n\n", arr3d_axis02)
print()

# Delete block 0 and 2
arr3d_axis01 = np.delete(arr3d,[0,2], axis=0)
print("\nWhole array after deletion of block 0 and 2:\n\n", arr3d_axis01)
print()

# Delete row 0 from each block
arr3d_axis1 = np.delete(arr3d, 0, axis=1)
print("\nWhole Array after deletion of row 0 from each block:\n\n", arr3d_axis1)
print()

# Delete col 0 and 1 from of block 0 using slicinig
arr3d_b0c01 = np.delete(arr3d[0], np.s_[0:2], axis=1)
print("\nBlock 0 after deletion of col 0 and 1 :\n\n", arr3d_b0c01)
print()

# Delete row 0 from of block 2
arr3d_b2r01 = np.delete(arr3d[2], 0, axis=0)
print("\nBlock 2 after deletion of row 0 :\n\n", arr3d_b2r01)
print()

# Delete col 1 from of block 1
arr3d_b1c1 = np.delete(arr3d[1],1, axis=1)
print("\nBlock 1 after deletion of col 1 :\n\n", arr3d_b1c1)
print()

# Delete col 0 and col 2 of block 2
arr3d_b2c02 = np.delete(arr3d[2],[0,2], axis=1)
print("\nBlock 2 after deletion of row 0 and 2 :\n\n", arr3d_b2c02)
print()

# Delete column 2 from each row in each block
arr3d_axis2 = np.delete(arr3d, 2, axis=2)
print("\nArray after deletion of column 2 from each row in each block:\n\n", arr3d_axis2)

Original new 3D array :

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

Delete block 1:

 [[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [16 17 18]]]


Array after deletion of block 0 and 1:

 [[[13 14 15]
  [16 17 18]]]


Whole array after deletion of block 0 and 2:

 [[[ 7  8  9]
  [10 11 12]]]


Whole Array after deletion of row 0 from each block:

 [[[ 4  5  6]]

 [[10 11 12]]

 [[16 17 18]]]


Block 0 after deletion of col 0 and 1 :

 [[3]
 [6]]


Block 2 after deletion of row 0 :

 [[16 17 18]]


Block 1 after deletion of col 1 :

 [[ 7  9]
 [10 12]]


Block 2 after deletion of row 0 and 2 :

 [[14]
 [17]]


Array after deletion of column 2 from each row in each block:

 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]
